# https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-features.html#gettingstarted-features-package

# More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900

Parameters: 
  DynamoDBCreationParameter: 
    Description: DynamoDBRecreation 0 o 1 to avoid deleting current data.
    Default: 0
    Type: String
    AllowedValues: 
      - 0
      - 1
    ConstraintDescription: must specify 0  or 1.
Conditions:
  CreateDynamoDBResourcesCondition: !Equals [!Ref DynamoDBCreationParameter, 1]
Resources:   
  #DynamoDBCustomResource:
  #  Type: AWS::CloudFormation::CustomResource
  #  Version: "1.0"
  #  Properties:
  #    ServiceToken: !GetAtt DynamoDBCustomResourceFunction.Arn
  #    #FunctionName: !Ref randomerror   
  DynamoDBCustomResourceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: DynamoDBCustomResourceFunction
      CodeUri: dynamodb_custom_resource_validator/
      Handler: app.lambda_handler      
      #Condition: CreateDynamoDBResourcesCondition
      Timeout: 120
      Runtime: python3.7      
      Environment:
        Variables:
          PatientsDynamoTable: !Ref AppCranealPatientDatesTable            
  SuscripSNSAppCranealPatientDates:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: david_nevado@yahoo.es
      Protocol: email
      TopicArn: !Ref AppCranealPatientDatesSNSTopicName
  SuscripSNSAppCranealPatientDates2:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: ana.maria.castano.leon@gmail.com
      Protocol: email
      TopicArn: !Ref AppCranealPatientDatesSNSTopicName
  CronSNSTopicCranealLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: {Service: [lambda.amazonaws.com]}
          Action: ['sts:AssumeRole']
      Path: /
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
      Policies:
      - PolicyName: SNSPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
              - "SNS:*" 
              Resource: ['*']    
  AppCranealSNSTopicCranealLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: {Service: [lambda.amazonaws.com]}
          Action: ['sts:AssumeRole']
      Path: /
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
      Policies:
      - PolicyName: SNSPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
              - "SNS:*" 
              Resource: ['*']    
  AppCranealPatientDatesSNSTopicName: 
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: AppCranealPatientDatesSNSTopicName      
      TopicName: AppCranealPatientDatesSNSTopicName        
  AppCranealPatientDatesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: appcranealpatientdates
  CronSNSTopicCranealFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: CronSNSTopicCranealFunction
      CodeUri: cron_sns_topic_cranealpatientdates/
      Handler: app.lambda_handler
      #Layers: https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html#configuration-layers-path
      #  - arn:aws:lambda:eu-central-1:291573578422:layer:layerpythoncranealpatientdates:2
      Timeout: 120
      Role: !GetAtt CronSNSTopicCranealLambdaExecutionRole.Arn
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess          
      Runtime: python3.7      
      Environment:
        Variables:
          PatientsDynamoTable: !Ref AppCranealPatientDatesTable          
          TopicArn: !Ref AppCranealPatientDatesSNSTopicName
          TargetBucket: appcranealpatientdates          
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(0 6 * * ? *) # 06:00  AM (UTC) every day
        CronSNSTopicCranealApi:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /cronsnstopiccraneal
            Method: get     
  AppCranealPatientDatesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: AppCranealPatientDatesFunction
      CodeUri: app_cranealpatientdates/
      Handler: app.lambda_handler      
      Timeout: 120
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess    
      Runtime: python3.7      
      Role: !GetAtt AppCranealSNSTopicCranealLambdaExecutionRole.Arn
      Environment:
        Variables:
          PatientsDynamoTable: !Ref AppCranealPatientDatesTable
          TargetBucket: appcranealpatientdates          
          TopicArn: !Ref AppCranealPatientDatesSNSTopicName
      Events:
        CreateAppCranealPatientDatesS3NewFile:
          Type: S3
          Properties:
            Bucket: !Ref AppCranealPatientDatesBucket
            Events: s3:ObjectCreated:*      
        AppCranealPatientDatesFunctionApi:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /appcranealpatientdates
            Method: get
  AppCranealPatientDatesTable:
    Type: AWS::DynamoDB::Table
    #Condition: CreateDynamoDBResourcesCondition
    #custom:
    #  dev:
    #    deletion_policy: Delete
    #  prod:
    #    deletion_policy: Retain
    DeletionPolicy: Retain
    Properties: 
      TableName : appcranealpatientdates
      AttributeDefinitions:                 
        - AttributeName: name
          AttributeType: S  
        - AttributeName: traumadate
          AttributeType: S  
        #- AttributeName: hnumber
        #  AttributeType: S 
        #- AttributeName: type
        #  AttributeType: S  
        #- AttributeName: sampletype
        #  AttributeType: S        
      KeySchema: 
        - AttributeName: name
          KeyType: HASH        
        - AttributeName: traumadate
          KeyType: RANGE
        #- AttributeName: hnumber
        #  KeyType: RANGE
        #- AttributeName: type
        #  KeyType: RANGE
        #- AttributeName: sampletype
        #  KeyType: RANGE      
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_IMAGE
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api  
  CronSNSTopicCranealFunction:
    Description: "CronSNSTopicCranealFunction Lambda Function ARN"
    Value: !GetAtt CronSNSTopicCranealFunction.Arn
  CronSNSTopicCranealFunctionIamRole:
    Description: "Implicit IAM Role created for CronSNSTopicCranealFunction function"
    Value: !GetAtt CronSNSTopicCranealFunction.Arn
  AppCranealPatientDatesFunction:
    Description: "AppCranealPatientDatesFunction Lambda Function ARN"
    Value: !GetAtt AppCranealPatientDatesFunction.Arn
  #AppCranealPatientDatesFunctionIamRole:
  # Description: "Implicit IAM Role created for AppCranealPatientDatesFunction function"
  #  Value: !GetAtt AppCranealPatientDatesFunctionRole.Arn    
  #DynamoDBExistsValidation:
  #    Value: !GetAtt DynamoDBCustomResourceFunction.DynamoDBExists